# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS_OMAP)		+= smartreflex.o
obj-$(CONFIG_QCOM_CPR)			+= qcom-cpr.o
obj-$(CONFIG_ROCKCHIP_IODOMAIN)		+= rockchip-io-domain.o
obj-$(CONFIG_MTK_SVS)			+= mtk_svs.o
